### ISSUE TITLE
Seed data creation swallows some exceptions and won't retry

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-config-dotnet#67]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Exceptions thrown when rules are not created or the simulation is not started, are logged and not re-thrown. This can lead to some deployments without seed data.

**Comment by cgritton** [comment]
FWIW, I'm seeing the same issue.  The first logged error I'm seeing is from storageadapter returning a 404 for solution-settings.seedcompleted.  Later, config "Failed to seed default rule Pressure > 250". followed by a config "Seed failed" message.
