### ISSUE TITLE
Bing Map Env Var Required

### ISSUE THREAD

**Issue by jdvachal** [Azure/pcs-config-dotnet#74]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

This service requires the environment variable PCS_BINGMAP_KEY to run, which is not validated or created in the env-var scripts.

# Steps to reproduce 

Run the web service without the PCS_BINGMAP_KEY defined.

# Expected behavior 

The webservice should start as expected.

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by ppathan** [comment]
Fixed
